--Guardar Backup
BACKUP DATABASE DBSISTEMA_VENTA
TO DISK = 'C:\Backups\DBSISTEMA_VENTA'
WITH INIT,
	STATS = 10;

--Cargar Backup
RESTORE DATABASE DBSISTEMA_VENTA
FROM DISK = 'C:\Backups\DBSISTEMA_VENTA'
WITH REPLACE,
	RECOVERY,
	STATS = 10;